betting_types = {
    1: '1x2',
    2: 'over under',
    3: 'home/away',
    4: 'dc',
    5: 'asian',
    6: 'draw no bet',
    7: 'to qualify',
    8: 'correct score',
    9: 'ht/ft',
    10: 'odd/even',
    12: 'euro handicap',
    13: 'both teams to score',
}

bookmakers = {
    '1': 'Interwetten',
    '2': 'bwin',
    '3': 'bet-at-home',
    '5': 'Unibet',
    '8': 'Stan James',
    '9': 'Expekt',
    '14': '10Bet',
    '15': 'William Hill',
    '16': 'bet365',
    '18': 'Pinnacle Sports',
    '20': '5Dimes',
    '21': 'Betfred',
    '23': 'DOXXbet',
    '24': 'Betsafe',
    '26': 'Betway',
    '27': '888sport',
    '28': 'Ladbrokes',
    '30': 'Boylesports',
    '31': 'Intertops',
    '32': 'Betclic',
    '33': 'NordicBet',
    '38': 'Sportingbet',
    '41': 'myBet',
    '43': 'Betsson',
    '45': 'Chance.cz',
    '46': 'iFortuna.cz',
    '49': 'Tipsport.cz',
    '53': 'bwin.it',
    '55': 'Noxwin',
    '56': '188BET',
    '57': 'Jetbull',
    '70': 'Tipico',
    '71': 'Coral',
    '73': 'LEON Bets',
    '75': 'SBOBET',
    '76': 'BetVictor',
    '78': 'BetOnline',
    '80': '12BET',
    '90': 'Betgun',
    '92': 'Island Casino',
    '98': 'Superbahis',
    '101': 'Paf',
    '103': 'Redbet',
    '121': 'Titanbet',
    '124': 'Luxbet',
    '125': 'Bestbet',
    '128': 'youwin',
    '129': 'bwin.fr',
    '139': 'France Pari',
    '140': 'Betclic.it',
    '147': 'Dafabet',
    '149': 'Interwetten.es',
    '157': 'Unibet.it',
    '160': 'Unibet.fr',
    '161': 'NetBet',
    '164': 'iFortuna.sk',
    '372': 'WilliamHill.it',
    '377': 'Bovada',
    '378': 'TonyBet',
    '379': 'PaddyPower.it',
    '381': 'MarathonBet',
    '384': 'bet-at-home.it',
    '390': 'Matchbook',
    '392': 'bwin.es',
    '393': 'Oddsring',
    '394': 'Tipico.it',
    '395': 'Tempobet',
    '397': 'Winlinebet',
    '399': 'Winner',
    '403': 'Betrally',
    '406': 'Sportium',
    '411': 'Tipsport.sk',
    '416': '18bet',
    '417': '1xbet',
    '418': 'Vernons',
    '419': 'bet365.it',
    '422': '5plusbet',
    '424': '138',
    '425': 'Realdealbet',
    '426': 'Otobet',
    '427': 'VitalBet',
}

leagues = [
    ["/albania/super-league/results", "Albania", "Super league", 1],
    ["/algeria/division-1/results", "Algeria", "Division 1", 1],
    ["/andorra/primera-divisio/results", "Andorra", "Primera Division", 1],
    ["/argentina/primera-division/results", "Argentina", "Primera Division", 1],
    ["/argentina/primera-b-nacional/results", "Argentina", "Primera B Nacional", 2],
    ["/argentina/primera-b-metropolitana/results", "Argentina", "Primera B Metropolitana", 3],
    ["/armenia/premier-league/results", "Armenia", "Premier League", 1],
    ["/australia/a-league/results", "Australia", "A league", 1],
    ["/austria/tipico-bundesliga/results", "Austria", "Tipico Bundesliga", 1],
    ["/austria/erste-liga/results", "Austria", "Erste Liga", 2],
    ["/azerbaijan/premier-league/results", "Azerbaijan", "Premier League", 1],
    ["/belarus/vysshaya-liga/results", "Belarus", "Vysshaya Liga", 1],
    ["/belgium/jupiler-league/results", "Belgium", "Jupiler League", 1],
    ["/belgium/proximus-league/results", "Belgium", "Proximus League", 2],
    ["/bosnia-and-herzegovina/premier-league/results", "Bosnia and Herzegovina", "Premier League", 1],
    ["/brazil/serie-a/results", "Brazil", "Serie A", 1],
    ["/brazil/serie-b/results", "Brazil", "Serie B", 2],
    ["/brazil/serie-c/results", "Brazil", "Serie C", 3],
    ["/brazil/serie-d/results", "Brazil", "Serie D", 4],
    ["/bulgaria/a-pfg/results", "Bulgaria", "A PFG", 1],
    ["/bulgaria/b-pfg/results", "Bulgaria", "B PFG", 2],
    ["/cameroon/elite-one/results", "Cameroon", "Elite One", 1],
    ["/canada/csl/results", "Canada", "CSL", 1],
    ["/chile/primera-division/results", "Chile", "Primera Division", 1],
    ["/chile/primera-b/results", "Chile", "Primera Division", 2],
    ["/china/super-league/results", "China", "Super League", 1],
    ["/china/jia-league/results", "China", "Jia League", 2],
    ["/colombia/liga-aguila/results", "Colombia", "Liga Aguila", 1],
    ["/colombia/torneo-aguila/results", "Colombia", "Torneo Aguila", 2],
    ["/costa-rica/primera-division/results", "Costa Rica", "Primera Division", 1],
    ["/croatia/1-hnl/results", "Croatia", "1 HNL", 1],
    ["/croatia/2-hnl/results", "Croatia", "2 NHL", 2],
    ["/czech-republic/synot-liga/results", "Czech Republic", "Synot Liga", 1],
    ["/czech-republic/division-2/results", "Czech Republic", "Division 2", 2],
    ["/denmark/superliga/results", "Denmark", "Superliga", 1],
    ["/denmark/bet25-liga/results", "Denmark", "Bet25 Liga", 2],
    ["/ecuador/serie-a/results", "Ecuador", "Serie A", 1],
    ["/egypt/premier-league/results", "Egypt", "Premier League", 1],
    ["/england/premier-league/results", "England", "Premier League", 1],
    ["/england/championship/results", "England", "Championship", 2],
    ["/england/league-one/results", "England", "League One", 3],
    ["/england/league-two/results", "England", "League Two", 4],
    ["/england/vanarama-national-league/results", "England", "Vanarama National League", 5],
    ["/estonia/meistriliiga/results", "Estonia", "Mestriliiga", 1],
    ["/estonia/esi-liiga/results", "Estonia", "Esi Liga", 2],
    ["/finland/veikkausliiga/results", "Finland", "Veikkausliiga", 1],
    ["/finland/ykkonen/results", "Finland", "Ykkonen", 2],
    ["/france/ligue-1/results", "France", "Ligue 1", 1],
    ["/france/ligue-2/results", "France", "Ligue 2", 2],
    ["/france/national/results", "France", "National", 3],
    ["/fyr-of-macedonia/first-league/results", "FYR of Macedonia", "First League", 1],
    ["/fyr-of-macedonia/division-1/results", "FYR of Macedonia", "Division 1", 2],
    ["/georgia/umaglesi-liga/results", "Georgia", "Umaglesi Liga", 1],
    ["/germany/bundesliga/results", "Germany", "Bundesliga", 1],
    ["/germany/2-bundesliga/results", "Germany", "2 Bundesliga", 2],
    ["/germany/3-liga/results", "Germany", "3 Bundesliga", 3],
    ["/ghana/premier-league/results", "Ghana", "Premier League", 1],
    ["/greece/super-league/results", "Greece", "Super League", 1],
    ["/honduras/liga-nacional/results", "Honduras", "Liga Nacional", 1],
    ["/hungary/otp-bank-liga/results", "Hungary", "OTP Bank Liga", 1],
    ["/hungary/merkantil-bank-liga/results", "Hungary", "Merkantil Bank Liga", 2],
    ["/iceland/pepsideild/results", "Iceland", "Pepsideild", 1],
    ["/iceland/division-1/results", "Iceland", "Division 1", 2],
    ["/iceland/division-2/results", "Iceland", "Division 2", 3],
    ["/iran/persian-gulf-pro-league/results", "Iran", "Persian Gulf Pro League", 1],
    ["/iran/division-1/results", "Iran", "Division 1", 2],
    ["/ireland/premier-league/results", "Ireland", "Premier League", 1],
    ["/ireland/division-1/results", "Ireland", "Division 1", 2],
    ["/italy/serie-a/results", "Italy", "Serie A", 1],
    ["/italy/serie-b/results", "Italy", "Serie B", 2],
    ["/italy/lega-pro-group-a/results", "Italy", "Lega Pro Group A", 3],
    ["/italy/lega-pro-group-b/results", "Italy", "Lega Pro Group B", 3],
    ["/italy/lega-pro-group-c/results", "Italy", "Lega Pro Group C", 3],
    ["/israel/ligat-ha-al/results", "Israel", "Ligat Ha al", 1],
    ["/israel/leumit-league/results", "Israel", "Leumit League", 2],
    ["/japan/j-league/results", "Japan", "J-League", 1],
    ["/japan/j-league-division-2/results", "Japan", "J-League Division 2", 2],
    ["/latvia/virsliga/results", "Latvia", "Virsliga", 1],
    ["/lithuania/a-lyga/results", "Lithuania", "A Lyga", 1],
    ["/mexico/primera-division/results", "Mexico", "Primera Division", 1],
    ["/mexico/liga-de-ascenso/results", "Mexico", "Liga de Ascenso", 2],
    ["/morocco/botola-pro/results", "Morroco", "Botola Pro", 1],
    ["/morocco/elite-2/results", "Morroco", "Elite 2", 2],
    ["/netherlands/eredivisie/results", "Netherlands", "Eredivisie", 1],
    ["/netherlands/eerste-divisie/results", "Netherlands", "Eerste Divisie", 2],
    ["/northern-ireland/nifl-premiership/results", "Northern Ireland", "NIFL Premiership", 1],
    ["/northern-ireland/ifa-championship-1/results", "Northern Ireland", "IFA Championship 1", 2],
    ["/norway/tippeligaen/results", "Norway", "Tippeligaen", 1],
    ["/norway/obos-ligaen/results", "Norway", "OBOS-ligaen", 2],
    ["/paraguay/primera-division/results", "Paraguay", "Primera Division", 1],
    ["/peru/primera-division/results", "Peru", "Primera Division", 1],
    ["/poland/ekstraklasa/results", "Poland", "Ekstraklasa", 1],
    ["/poland/division-1/results", "Poland", "Division 1", 2],
    ["/poland/division-2/results", "Poland", "Division 2", 3],
    ["/portugal/primeira-liga/results", "Portugal", "Primeira Liga", 1],
    ["/portugal/segunda-liga/results", "Portugal", "Segunda Liga", 2],
    ["/portugal/campeonato-nacional/results", "Portugal", "Compeonato Nacional", 3],
    ["/qatar/premier-league/results", "Quatar", "Premier League", 1],
    ["/romania/liga-1/results", "Romania", "Liga 1", 1],
    ["/russia/premier-league/results", "Russia", "Premier League", 1],
    ["/russia/division-1/results", "Russia", "Division 1", 2],
    ["/saudi-arabia/saudi-professional-league/results", "Saudi Arabia", "Saudi Professional League", 1],
    ["/saudi-arabia/division-1/results", "Saudi Arabia", "Division 1", 2],
    ["/scotland/premiership/results", "Scotland", "Premiership", 1],
    ["/scotland/championship/results", "Scotland", "Championship", 2],
    ["/scotland/league-one/results", "Scotland", "League One", 3],
    ["/scotland/league-two/results", "Scotland", "League Two", 4],
    ["/slovakia/fortuna-liga/results", "Slovakia", "Fortuna Liga", 1],
    ["/slovenia/prva-liga/results", "Slovenia", "Prva Liga", 1],
    ["/slovenia/2-snl/results", "Slovenia", "2 SNL", 2],
    ["/south-africa/premier-league/results", "South Africa", "Premier League", 1],
    ["/south-africa/first-division/results", "South Africa", "First Division", 2],
    ["/south-korea/k-league-classic/results", "South Korea", "K League Classic", 1],
    ["/south-korea/k-league-challenge/results", "South Korea", "K League Challenge", 2],
    ["/spain/primera-division/results", "Spain", "Primera Division", 1],
    ["/spain/segunda-division/results", "Spain", "Segunda Division", 2],
    ["/spain/segunda-division-b-group-1/results", "Spain", "Segunda Division B1", 3],
    ["/spain/segunda-division-b-group-2/results", "Spain", "Segunda Division B2", 3],
    ["/spain/segunda-division-b-group-3/results", "Spain", "Segunda Division B3", 3],
    ["/spain/segunda-division-b-group-4/results", "Spain", "Segunda Division B4", 3],
    ["/sweden/allsvenskan/results", "Sweden", "Allsvenskan", 1],
    ["/sweden/superettan/results", "Sweden", "Superettan", 2],
    ["/switzerland/super-league/results", "Switzerland", "Super League", 1],
    ["/switzerland/challenge-league/results", "Switzerland", "Challenge League", 2],
    ["/turkey/super-lig/results", "Turkey", "Super Lig", 1],
    ["/turkey/ptt-1-lig/results", "Turkey", "PTT 1 Lig", 2],
    ["/turkey/tff-2-lig-white-group/results", "Turkey", "TFF 2 Lig White", 3],
    ["/turkey/tff-2-lig-red-group/results", "Turkey", "TFF 2 Lig Red", 3],
    ["/ukraine/pari-match-league/results", "Ukraine", "Pari Match League", 1],
    ["/ukraine/division-2/results", "Ukraine", "Division 2", 2],
    ["/united-arab-emirates/uae-league/results", "United Arab Emirates", "UAE League", 1],
    ["/uruguay/primera-division/results", "Uruguay", "Primera Division", 1],
    ["/usa/mls/results", "USA", "MLS", 1],
    ["/venezuela/primera-division/results", "Venezuela", "Primera Division", 1],
    ["/wales/premier-league/results", "Wales", "Premier League", 1],
    ["/wales/division-1/results", "Wales", "Premier League", 2],
]
